module Evergreen.Migrate.V22 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V15.Bridge
import Evergreen.V15.Page
import Evergreen.V15.Page.Home
import Evergreen.V15.Shared
import Evergreen.V15.Types
import Evergreen.V22.Bridge
import Evergreen.V22.Page
import Evergreen.V22.Page.Home
import Evergreen.V22.Shared
import Evergreen.V22.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V15.Types.FrontendModel -> ModelMigration Evergreen.V22.Types.FrontendModel Evergreen.V22.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V15.Types.BackendModel -> ModelMigration Evergreen.V22.Types.BackendModel Evergreen.V22.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V15.Types.FrontendMsg -> MsgMigration Evergreen.V22.Types.FrontendMsg Evergreen.V22.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V15.Types.ToBackend -> MsgMigration Evergreen.V22.Types.ToBackend Evergreen.V22.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V15.Types.BackendMsg -> MsgMigration Evergreen.V22.Types.BackendMsg Evergreen.V22.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V15.Types.ToFrontend -> MsgMigration Evergreen.V22.Types.ToFrontend Evergreen.V22.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V15.Types.BackendModel -> Evergreen.V22.Types.BackendModel
migrate_Types_BackendModel old =
    { fetchMiracleConsecutiveFails = 0
    , miracleRookHighscores = Dict.empty
    }


migrate_Types_FrontendModel : Evergreen.V15.Types.FrontendModel -> Evergreen.V22.Types.FrontendModel
migrate_Types_FrontendModel old =
    { page = old.page |> migrate_Page_Model
    , shared = old.shared |> migrate_Shared_Model
    }


migrate_Types_ToBackend : Evergreen.V15.Types.ToBackend -> Evergreen.V22.Types.ToBackend
migrate_Types_ToBackend old =
    old |> migrate_Bridge_ToBackend


migrate_Bridge_ToBackend : Evergreen.V15.Bridge.ToBackend -> Evergreen.V22.Bridge.ToBackend
migrate_Bridge_ToBackend old =
    case old of
        Evergreen.V15.Bridge.DoNothing ->
            Evergreen.V22.Bridge.DoNothing


migrate_Page_Home_FightStance : Evergreen.V15.Page.Home.FightStance -> Evergreen.V22.Page.Home.FightStance
migrate_Page_Home_FightStance old =
    case old of
        Evergreen.V15.Page.Home.FightStanceOffensive ->
            Evergreen.V22.Page.Home.FightStanceOffensive

        Evergreen.V15.Page.Home.FightStanceBalanced ->
            Evergreen.V22.Page.Home.FightStanceBalanced

        Evergreen.V15.Page.Home.FightStanceDefensive ->
            Evergreen.V22.Page.Home.FightStanceDefensive


migrate_Page_Home_Model : Evergreen.V15.Page.Home.Model -> Evergreen.V22.Page.Home.Model
migrate_Page_Home_Model old =
    { meleeFightStance = old.meleeFightStance |> migrate_Page_Home_FightStance
    , meleeLevel = old.meleeLevel
    , meleeSkill = old.meleeSkill
    , meleeAttack = old.meleeAttack
    , meleeStrength = old.meleeStrength
    , meleeMonster = old.meleeMonster
    , distanceFightStance = old.distanceFightStance |> migrate_Page_Home_FightStance
    , distanceLevel = old.distanceLevel
    , distanceSkill = old.distanceSkill
    , distanceAttack = old.distanceAttack
    , distanceDexterity = old.distanceDexterity
    , distanceMonster = old.distanceMonster
    , blockingFightStance = old.blockingFightStance |> migrate_Page_Home_FightStance
    , blockingSkill = old.blockingSkill
    , blockingDefense = old.blockingDefense
    , totalArmor = old.totalArmor
    , worldType = old.worldType |> migrate_Page_Home_WorldType
    , skillDistanceFrom = old.skillDistanceFrom
    , skillDistanceTo = old.skillDistanceTo
    , skillDistancePercentToGo = old.skillDistancePercentToGo
    , skillMeleeFrom = old.skillMeleeFrom
    , skillMeleeTo = old.skillMeleeTo
    , skillMeleePercentToGo = old.skillMeleePercentToGo
    , skillBlockingFrom = old.skillBlockingFrom
    , skillBlockingTo = old.skillBlockingTo
    , skillBlockingPercentToGo = old.skillBlockingPercentToGo
    , magicLevelFrom = old.magicLevelFrom
    , magicLevelTo = old.magicLevelTo
    , magicLevelPercentToGo = old.magicLevelPercentToGo
    , skillFishingFrom = old.skillFishingFrom
    , skillFishingTo = old.skillFishingTo
    , skillFishingPercentToGo = old.skillFishingPercentToGo
    , upLevelFrom = old.upLevelFrom
    , upLevelTo = old.upLevelTo
    , upPercentToGo = old.upPercentToGo
    , upXph = old.upXph
    }


migrate_Page_Home_Msg : Evergreen.V15.Page.Home.Msg -> Evergreen.V22.Page.Home.Msg
migrate_Page_Home_Msg old =
    case old of
        Evergreen.V15.Page.Home.InputMeleeFightStance p0 ->
            Evergreen.V22.Page.Home.InputMeleeFightStance (p0 |> migrate_Page_Home_FightStance)

        Evergreen.V15.Page.Home.InputMeleeLevel p0 ->
            Evergreen.V22.Page.Home.InputMeleeLevel p0

        Evergreen.V15.Page.Home.InputMeleeSkill p0 ->
            Evergreen.V22.Page.Home.InputMeleeSkill p0

        Evergreen.V15.Page.Home.InputMeleeAttack p0 ->
            Evergreen.V22.Page.Home.InputMeleeAttack p0

        Evergreen.V15.Page.Home.InputMeleeStrength p0 ->
            Evergreen.V22.Page.Home.InputMeleeStrength p0

        Evergreen.V15.Page.Home.InputMeleeMonster p0 ->
            Evergreen.V22.Page.Home.InputMeleeMonster p0

        Evergreen.V15.Page.Home.InputDistanceFightStance p0 ->
            Evergreen.V22.Page.Home.InputDistanceFightStance (p0 |> migrate_Page_Home_FightStance)

        Evergreen.V15.Page.Home.InputDistanceLevel p0 ->
            Evergreen.V22.Page.Home.InputDistanceLevel p0

        Evergreen.V15.Page.Home.InputDistanceSkill p0 ->
            Evergreen.V22.Page.Home.InputDistanceSkill p0

        Evergreen.V15.Page.Home.InputDistanceAttack p0 ->
            Evergreen.V22.Page.Home.InputDistanceAttack p0

        Evergreen.V15.Page.Home.InputDistanceDexterity p0 ->
            Evergreen.V22.Page.Home.InputDistanceDexterity p0

        Evergreen.V15.Page.Home.InputDistanceMonster p0 ->
            Evergreen.V22.Page.Home.InputDistanceMonster p0

        Evergreen.V15.Page.Home.InputBlockingFightStance p0 ->
            Evergreen.V22.Page.Home.InputBlockingFightStance (p0 |> migrate_Page_Home_FightStance)

        Evergreen.V15.Page.Home.InputBlockingSkill p0 ->
            Evergreen.V22.Page.Home.InputBlockingSkill p0

        Evergreen.V15.Page.Home.InputBlockingDefense p0 ->
            Evergreen.V22.Page.Home.InputBlockingDefense p0

        Evergreen.V15.Page.Home.InputTotalArmor p0 ->
            Evergreen.V22.Page.Home.InputTotalArmor p0

        Evergreen.V15.Page.Home.InputWorldType p0 ->
            Evergreen.V22.Page.Home.InputWorldType (p0 |> migrate_Page_Home_WorldType)

        Evergreen.V15.Page.Home.InputSkillDistanceFrom p0 ->
            Evergreen.V22.Page.Home.InputSkillDistanceFrom p0

        Evergreen.V15.Page.Home.InputSkillDistanceTo p0 ->
            Evergreen.V22.Page.Home.InputSkillDistanceTo p0

        Evergreen.V15.Page.Home.InputSkillDistancePercentToGo p0 ->
            Evergreen.V22.Page.Home.InputSkillDistancePercentToGo p0

        Evergreen.V15.Page.Home.InputSkillMeleeFrom p0 ->
            Evergreen.V22.Page.Home.InputSkillMeleeFrom p0

        Evergreen.V15.Page.Home.InputSkillMeleeTo p0 ->
            Evergreen.V22.Page.Home.InputSkillMeleeTo p0

        Evergreen.V15.Page.Home.InputSkillMeleePercentToGo p0 ->
            Evergreen.V22.Page.Home.InputSkillMeleePercentToGo p0

        Evergreen.V15.Page.Home.InputSkillBlockingFrom p0 ->
            Evergreen.V22.Page.Home.InputSkillBlockingFrom p0

        Evergreen.V15.Page.Home.InputSkillBlockingTo p0 ->
            Evergreen.V22.Page.Home.InputSkillBlockingTo p0

        Evergreen.V15.Page.Home.InputSkillBlockingPercentToGo p0 ->
            Evergreen.V22.Page.Home.InputSkillBlockingPercentToGo p0

        Evergreen.V15.Page.Home.InputMagicLevelFrom p0 ->
            Evergreen.V22.Page.Home.InputMagicLevelFrom p0

        Evergreen.V15.Page.Home.InputMagicLevelTo p0 ->
            Evergreen.V22.Page.Home.InputMagicLevelTo p0

        Evergreen.V15.Page.Home.InputMagicLevelPercentToGo p0 ->
            Evergreen.V22.Page.Home.InputMagicLevelPercentToGo p0

        Evergreen.V15.Page.Home.InputSkillFishingFrom p0 ->
            Evergreen.V22.Page.Home.InputSkillFishingFrom p0

        Evergreen.V15.Page.Home.InputSkillFishingTo p0 ->
            Evergreen.V22.Page.Home.InputSkillFishingTo p0

        Evergreen.V15.Page.Home.InputSkillFishingPercentToGo p0 ->
            Evergreen.V22.Page.Home.InputSkillFishingPercentToGo p0

        Evergreen.V15.Page.Home.InputUpLevelFrom p0 ->
            Evergreen.V22.Page.Home.InputUpLevelFrom p0

        Evergreen.V15.Page.Home.InputUpLevelTo p0 ->
            Evergreen.V22.Page.Home.InputUpLevelTo p0

        Evergreen.V15.Page.Home.InputUpPercentToGo p0 ->
            Evergreen.V22.Page.Home.InputUpPercentToGo p0

        Evergreen.V15.Page.Home.InputUpXph p0 ->
            Evergreen.V22.Page.Home.InputUpXph p0


migrate_Page_Home_WorldType : Evergreen.V15.Page.Home.WorldType -> Evergreen.V22.Page.Home.WorldType
migrate_Page_Home_WorldType old =
    case old of
        Evergreen.V15.Page.Home.WorldTypeSlow ->
            Evergreen.V22.Page.Home.WorldTypeSlow

        Evergreen.V15.Page.Home.WorldTypeFast ->
            Evergreen.V22.Page.Home.WorldTypeFast


migrate_Page_Model : Evergreen.V15.Page.Model -> Evergreen.V22.Page.Model
migrate_Page_Model old =
    case old of
        Evergreen.V15.Page.Home p0 ->
            Evergreen.V22.Page.Home (p0 |> migrate_Page_Home_Model)

        Evergreen.V15.Page.NotFound ->
            Evergreen.V22.Page.NotFound


migrate_Page_Msg : Evergreen.V15.Page.Msg -> Evergreen.V22.Page.Msg
migrate_Page_Msg old =
    case old of
        Evergreen.V15.Page.HomeMsg p0 ->
            Evergreen.V22.Page.HomeMsg (p0 |> migrate_Page_Home_Msg)


migrate_Shared_Model : Evergreen.V15.Shared.Model -> Evergreen.V22.Shared.Model
migrate_Shared_Model old =
    old


migrate_Shared_Msg : Evergreen.V15.Shared.Msg -> Evergreen.V22.Shared.Msg
migrate_Shared_Msg old =
    case old of
        Evergreen.V15.Shared.GotViewport p0 ->
            Evergreen.V22.Shared.GotViewport p0

        Evergreen.V15.Shared.OnResize p0 p1 ->
            Evergreen.V22.Shared.OnResize p0 p1

        Evergreen.V15.Shared.GotZone p0 ->
            Evergreen.V22.Shared.GotZone p0


migrate_Types_BackendMsg : Evergreen.V15.Types.BackendMsg -> Evergreen.V22.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V15.Types.BackendMsg_DoNothing ->
            Evergreen.V22.Types.BackendMsg_DoNothing


migrate_Types_FrontendMsg : Evergreen.V15.Types.FrontendMsg -> Evergreen.V22.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V15.Types.FrontendMsg_DoNothing ->
            Evergreen.V22.Types.FrontendMsg_DoNothing

        Evergreen.V15.Types.FrontendMsg_UrlClicked p0 ->
            Evergreen.V22.Types.FrontendMsg_UrlClicked p0

        Evergreen.V15.Types.FrontendMsg_UrlChanged p0 ->
            Evergreen.V22.Types.FrontendMsg_UrlChanged p0

        Evergreen.V15.Types.FrontendMsg_PageMsg p0 ->
            Evergreen.V22.Types.FrontendMsg_PageMsg (p0 |> migrate_Page_Msg)

        Evergreen.V15.Types.FrontendMsg_SharedMsg p0 ->
            Evergreen.V22.Types.FrontendMsg_SharedMsg (p0 |> migrate_Shared_Msg)


migrate_Types_ToFrontend : Evergreen.V15.Types.ToFrontend -> Evergreen.V22.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V15.Types.ToFrontend_DoNothing ->
            Evergreen.V22.Types.ToFrontend_DoNothing

        Evergreen.V15.Types.ToFrontend_PageMsg p0 ->
            Evergreen.V22.Types.ToFrontend_PageMsg (p0 |> migrate_Page_Msg)
